CREATE TABLE Invoice (
	InvoiceID INT NOT NULL AUTO_INCREMENT,
    OrderID  INT NOT NULL,
    InvoiceDate DATETIME,
    InvoiceStatus CHAR(20),
    PRIMARY KEY(InvoiceID),
    CONSTRAINT FK_OrderID FOREIGN KEY (OrderID) REFERENCES Orders (OrderID) ON UPDATE CASCADE
)AUTO_INCREMENT=343091;