CREATE TABLE Product_Order(
	ProductOrderID INT NOT NULL AUTO_INCREMENT,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    ProductName CHAR(20),
    Quantity INT,
    Price DECIMAL(20,2),
    PRIMARY KEY(ProductOrderID),
    CONSTRAINT FK_productID FOREIGN KEY (ProductID) REFERENCES Products (ProductID) ON UPDATE CASCADE,
    CONSTRAINT FK_order FOREIGN KEY (OrderID) REFERENCES Orders (OrderID) ON UPDATE CASCADE
)AUTO_INCREMENT=46424;